---
- name: "Enable userpass authentication"
  ansible.builtin.command:
    cmd: "/usr/local/bin/vault auth enable userpass"
    creates: "{{ vault_home_dir }}/userpass_enabled"
  register: auth_result

- name: "Create a marker file for userpass enablement"
  ansible.builtin.file:
    path: "{{ vault_home_dir }}/userpass_enabled"
    state: touch
  when: auth_result.rc == 0

- name: "Create a user with userpass"
  ansible.builtin.command:
    cmd: "/usr/local/bin/vault write auth/userpass/users/{{ vault_user }} password={{ vault_passwd }} policies={{ policy }}"
  vars:
    policy: "default"