---
# vars file for vault
vault_server_ip_addr : "{{ hostvars[inventory_hostname]['server_internal_ip'] }}"
vault_server_port: 8200
tls_disable: true
vault_storage_file: "/opt/vault/data"
vault_addr: "http://{{ vault_server_ip_addr }}:{{ vault_server_port }}"
vault_user: "pocmaster"
vault_passwd: "pocmaster"